config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/john-shepherdson/eosc.node-registry.demo:
      branch: main
      repo: https://github.com/john-shepherdson/eosc.node-registry.demo.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/john-shepherdson/eosc.node-registry.demo git:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-harlequin-dachshund.sh
        container: qc.acc_shabby-coral-bulldog
  QC.Doc:
    repos:
      github.com/john-shepherdson/eosc.node-registry.demo find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-cerise-chihuahua.sh
        container: qc.doc_clammy-chartreuse-cassowary
      github.com/john-shepherdson/eosc.node-registry.demo git:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-brown-impala.sh
        container: qc.doc_muggy-green-rat
      github.com/john-shepherdson/eosc.node-registry.demo markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-eggplant-bloodhound.sh
        container: qc.doc_hazy-orchid-grouse
  QC.Lic:
    repos:
      github.com/john-shepherdson/eosc.node-registry.demo licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-bistre-numbat.sh
        container: qc.lic_scummy-tomato-guppy
  QC.Met:
    repos:
      github.com/john-shepherdson/eosc.node-registry.demo cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-rose-maltese.sh
        container: qc.met_skanky-bistre-hyrax
  QC.Sty:
    repos:
      github.com/john-shepherdson/eosc.node-registry.demo checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-rust-boar.sh
        container: qc.sty_pretty-linen-setter
      github.com/john-shepherdson/eosc.node-registry.demo hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-magenta-cuscus.sh
        container: qc.sty_cloudy-chartreuse-rabbit
      github.com/john-shepherdson/eosc.node-registry.demo jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-puce-cuscus.sh
        container: qc.sty_pretty-red-squirt
  QC.Ver:
    repos:
      github.com/john-shepherdson/eosc.node-registry.demo get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-sangria-toad.sh
        container: qc.ver_shaky-pumpkin-kakapo
timeout: 5400
