config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/john-shepherdson/eosc.node-registry.demo:
      branch: main
      repo: https://github.com/john-shepherdson/eosc.node-registry.demo.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/john-shepherdson/eosc.node-registry.demo git:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-turquoise-chin.sh
        container: qc.acc_whiny-orange-earwig
  QC.Doc:
    repos:
      github.com/john-shepherdson/eosc.node-registry.demo find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-razzmatazz-meerkat.sh
        container: qc.doc_breezy-green-mongoose
      github.com/john-shepherdson/eosc.node-registry.demo git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-brass-cougar.sh
        container: qc.doc_blurry-blue-dog
      github.com/john-shepherdson/eosc.node-registry.demo markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-myrtle-corgi.sh
        container: qc.doc_crappy-orange-whippet
  QC.Lic:
    repos:
      github.com/john-shepherdson/eosc.node-registry.demo licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-lemon-rattlesnake.sh
        container: qc.lic_woolly-zucchini-scorpion
  QC.Met:
    repos:
      github.com/john-shepherdson/eosc.node-registry.demo cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-cornflower-foxhound.sh
        container: qc.met_lousy-grey-quokka
  QC.Sty:
    repos:
      github.com/john-shepherdson/eosc.node-registry.demo checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-myrtle-wolf.sh
        container: qc.sty_beady-indigo-dolphin
      github.com/john-shepherdson/eosc.node-registry.demo hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-mustard-setter.sh
        container: qc.sty_stinky-vermilion-coral
  QC.Ver:
    repos:
      github.com/john-shepherdson/eosc.node-registry.demo get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-red-newt.sh
        container: qc.ver_whiny-eggplant-macaque
timeout: 5400
