config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/john-shepherdson/eosc.node-registry.demo:
      branch: main
      repo: https://github.com/john-shepherdson/eosc.node-registry.demo.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/john-shepherdson/eosc.node-registry.demo git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-viridian-insect.sh
        container: qc.acc_slaphappy-saffron-penguin
  QC.Doc:
    repos:
      github.com/john-shepherdson/eosc.node-registry.demo find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-salmon-liger.sh
        container: qc.doc_chummy-plum-cockroach
      github.com/john-shepherdson/eosc.node-registry.demo git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-taupe-mist.sh
        container: qc.doc_squeaky-sepia-goose
      github.com/john-shepherdson/eosc.node-registry.demo markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-sepia-robin.sh
        container: qc.doc_homey-ecru-caracal
  QC.Lic:
    repos:
      github.com/john-shepherdson/eosc.node-registry.demo licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-taupe-setter.sh
        container: qc.lic_gloppy-maroon-dragon
  QC.Met:
    repos:
      github.com/john-shepherdson/eosc.node-registry.demo cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-mauve-grouse.sh
        container: qc.met_queasy-asparagus-wrasse
  QC.Sty:
    repos:
      github.com/john-shepherdson/eosc.node-registry.demo checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-olive-giraffe.sh
        container: qc.sty_lovely-lilac-tetra
      github.com/john-shepherdson/eosc.node-registry.demo hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-magenta-wolverine.sh
        container: qc.sty_foggy-amethyst-leopard
      github.com/john-shepherdson/eosc.node-registry.demo jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-sepia-panda.sh
        container: qc.sty_crappy-ochre-binturong
  QC.Ver:
    repos:
      github.com/john-shepherdson/eosc.node-registry.demo get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-periwinkle-russel.sh
        container: qc.ver_hilly-violet-slug
timeout: 5400
