config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/john-shepherdson/eosc.node-registry.demo:
      branch: main
      repo: https://github.com/john-shepherdson/eosc.node-registry.demo.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/john-shepherdson/eosc.node-registry.demo git:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-ivory-raccoon.sh
        container: qc.acc_blurry-green-cuttlefish
  QC.Doc:
    repos:
      github.com/john-shepherdson/eosc.node-registry.demo find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-amethyst-deer.sh
        container: qc.doc_sloppy-cerise-devil
      github.com/john-shepherdson/eosc.node-registry.demo git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-zucchini-zonkey.sh
        container: qc.doc_breezy-red-seal
      github.com/john-shepherdson/eosc.node-registry.demo markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-lemon-macaque.sh
        container: qc.doc_pokey-cerulean-serval
  QC.Lic:
    repos:
      github.com/john-shepherdson/eosc.node-registry.demo licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-coral-rhinoceros.sh
        container: qc.lic_scaly-pear-bird
  QC.Met:
    repos:
      github.com/john-shepherdson/eosc.node-registry.demo cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-smalt-abyssinian.sh
        container: qc.met_boozy-purple-bat
  QC.Sty:
    repos:
      github.com/john-shepherdson/eosc.node-registry.demo checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-smalt-caiman.sh
        container: qc.sty_woozy-russet-chinook
      github.com/john-shepherdson/eosc.node-registry.demo hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-bistre-bird.sh
        container: qc.sty_stealthy-xanthic-leopard
  QC.Ver:
    repos:
      github.com/john-shepherdson/eosc.node-registry.demo get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-wheat-dragonfly.sh
        container: qc.ver_hazy-cerulean-insect
timeout: 5400
