config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/john-shepherdson/eosc.node-registry.demo:
      branch: main
      repo: https://github.com/john-shepherdson/eosc.node-registry.demo.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/john-shepherdson/eosc.node-registry.demo git:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-azure-malamute.sh
        container: qc.acc_goopy-magnolia-wallaby
  QC.Doc:
    repos:
      github.com/john-shepherdson/eosc.node-registry.demo find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-lilac-birman.sh
        container: qc.doc_flabby-puce-fowl
      github.com/john-shepherdson/eosc.node-registry.demo git:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-white-bee.sh
        container: qc.doc_gamy-seashell-cuttlefish
      github.com/john-shepherdson/eosc.node-registry.demo markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-sepia-maltese.sh
        container: qc.doc_messy-asparagus-kiwi
  QC.Lic:
    repos:
      github.com/john-shepherdson/eosc.node-registry.demo licensee:
        commands:
        - /usr/bin/env sh .sqa/script.surly-cinnamon-cat.sh
        container: qc.lic_ugly-chartreuse-woodpecker
  QC.Met:
    repos:
      github.com/john-shepherdson/eosc.node-registry.demo cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-pear-millipede.sh
        container: qc.met_leaky-magnolia-chameleon
  QC.Sty:
    repos:
      github.com/john-shepherdson/eosc.node-registry.demo checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.silly-yellow-impala.sh
        container: qc.sty_shaky-orchid-horse
      github.com/john-shepherdson/eosc.node-registry.demo hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-pink-havanese.sh
        container: qc.sty_cloudy-sepia-serval
      github.com/john-shepherdson/eosc.node-registry.demo jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-amber-impala.sh
        container: qc.sty_skanky-xanthic-harrier
  QC.Ver:
    repos:
      github.com/john-shepherdson/eosc.node-registry.demo get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-azure-kangaroo.sh
        container: qc.ver_squeaky-turquoise-foxhound
timeout: 5400
